#include "flipmatrix.h"
#include <furi_hal_spi_config.h>
#include <furi_hal_resources.h>
#include <string.h>
/* generated by fbt from .png files in images folder */
#include <flipmatrix_icons.h>

void flipmatrix_menu_callback(void* context, uint32_t index) {
    App* app = context;
    switch(index) {
    case FlipMatrixMainMenuSceneConnect:
        scene_manager_handle_custom_event(app->scene_manager, FlipMatrixMainMenuSceneConnectEvent);
        break;
    case FlipMatrixMainMenuSceneHowToConnect:
        scene_manager_handle_custom_event(
            app->scene_manager, FlipMatrixMainMenuSceneHowToConnectEvent);
        break;
    case FlipMatrixMainMenuSceneAbout:
        scene_manager_handle_custom_event(app->scene_manager, FlipMatrixMainMenuSceneAboutEvent);
        break;
    }
}

void flipmatrix_main_menu_scene_on_enter(void* context) {
    App* app = context;
    submenu_reset(app->submenu);
    submenu_set_header(app->submenu, "FlipMatrix");
    submenu_add_item(
        app->submenu, "Connect", FlipMatrixMainMenuSceneConnect, flipmatrix_menu_callback, app);
    submenu_add_item(
        app->submenu,
        "How to connect",
        FlipMatrixMainMenuSceneHowToConnect,
        flipmatrix_menu_callback,
        app);
    submenu_add_item(
        app->submenu, "About", FlipMatrixMainMenuSceneAbout, flipmatrix_menu_callback, app);
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipMatrixSubmenuView);
}

bool flipmatrix_main_menu_scene_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case FlipMatrixMainMenuSceneConnectEvent:
            scene_manager_next_scene(app->scene_manager, FlipMatrixConnectScene);
            consumed = true;
            break;
        case FlipMatrixMainMenuSceneHowToConnectEvent:
            scene_manager_next_scene(app->scene_manager, FlipMatrixHowToConnectScene);
            consumed = true;
            break;
        case FlipMatrixMainMenuSceneAboutEvent:
            scene_manager_next_scene(app->scene_manager, FlipMatrixAboutScene);
            consumed = true;
            break;
        }
        break;
    default:
        break;
    }
    return consumed;
}

void flipmatrix_main_menu_scene_on_exit(void* context) {
    App* app = context;
    submenu_reset(app->submenu);
}

void flipmatrix_connect_scene_on_enter(void* context) {
    App* app = context;
    widget_reset(app->widget);

    if(!app->matrix_connected) {
        // Try to initialize MAX7219
        if(max7219_init(app->max7219)) {
            app->matrix_connected = true;

            // Test individual pixels
            max7219_clear_display(app->max7219);
            max7219_set_pixel(app->max7219, 0, 0, true); // Top-left
            max7219_set_pixel(app->max7219, 0, 7, true); // Top-right
            max7219_set_pixel(app->max7219, 7, 0, true); // Bottom-left
            max7219_set_pixel(app->max7219, 7, 7, true); // Bottom-right
            max7219_set_pixel(app->max7219, 3, 3, true); // Center-left
            max7219_set_pixel(app->max7219, 3, 4, true); // Center-right
            max7219_set_pixel(app->max7219, 4, 3, true); // Center-left
            max7219_set_pixel(app->max7219, 4, 4, true); // Center-right

            widget_add_string_element(
                app->widget, 64, 15, AlignCenter, AlignCenter, FontPrimary, "MAX7219 Connected!");
            widget_add_string_element(
                app->widget, 64, 30, AlignCenter, AlignCenter, FontSecondary, "LED Matrix Active");
            widget_add_string_element(
                app->widget,
                64,
                45,
                AlignCenter,
                AlignCenter,
                FontSecondary,
                "Demo patterns shown");
        } else {
            widget_add_string_element(
                app->widget, 64, 20, AlignCenter, AlignCenter, FontPrimary, "Connection Failed");
            widget_add_string_element(
                app->widget, 64, 35, AlignCenter, AlignCenter, FontSecondary, "Check wiring");
        }
    } else {
        widget_add_string_element(
            app->widget, 64, 15, AlignCenter, AlignCenter, FontPrimary, "Already Connected");
        widget_add_string_element(
            app->widget, 64, 30, AlignCenter, AlignCenter, FontSecondary, "MAX7219 Active");

        // Demo shifting animation
        while(1) {
            max7219_shift_left(app->max7219, true); // Shift left with wrap
            furi_delay_ms(100); // Brief delay
        }
        widget_add_string_element(
            app->widget, 64, 45, AlignCenter, AlignCenter, FontSecondary, "Animation demo");
    }

    view_dispatcher_switch_to_view(app->view_dispatcher, FlipMatrixWidgetView);
}

bool flipmatrix_connect_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false; // event not handled.
}

void flipmatrix_connect_scene_on_exit(void* context) {
    App* app = context;
    widget_reset(app->widget);
}

void flipmatrix_how_to_connect_scene_on_enter(void* context) {
    App* app = context;

    furi_string_reset(app->text_box_store);
    furi_string_cat_str(app->text_box_store, FLIPMATRIX_HOW_TO_CONNECT_TEXT);

    text_box_reset(app->text_box);
    text_box_set_text(app->text_box, furi_string_get_cstr(app->text_box_store));
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipMatrixTextBoxView);
}

bool flipmatrix_how_to_connect_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false; // event not handled.
}

void flipmatrix_how_to_connect_scene_on_exit(void* context) {
    App* app = context;
    text_box_reset(app->text_box);
}

void flipmatrix_about_scene_on_enter(void* context) {
    App* app = context;

    furi_string_reset(app->text_box_store);
    furi_string_cat_str(app->text_box_store, FLIPMATRIX_ABOUT_TEXT);

    text_box_reset(app->text_box);
    text_box_set_text(app->text_box, furi_string_get_cstr(app->text_box_store));
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipMatrixTextBoxView);
}

bool flipmatrix_about_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false; // event not handled.
}

void flipmatrix_about_scene_on_exit(void* context) {
    App* app = context;
    text_box_reset(app->text_box);
}

void (*const flipmatrix_scene_on_enter_handlers[])(void*) = {
    flipmatrix_main_menu_scene_on_enter,
    flipmatrix_connect_scene_on_enter,
    flipmatrix_how_to_connect_scene_on_enter,
    flipmatrix_about_scene_on_enter,
};

bool (*const flipmatrix_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    flipmatrix_main_menu_scene_on_event,
    flipmatrix_connect_scene_on_event,
    flipmatrix_how_to_connect_scene_on_event,
    flipmatrix_about_scene_on_event,
};

void (*const flipmatrix_scene_on_exit_handlers[])(void*) = {
    flipmatrix_main_menu_scene_on_exit,
    flipmatrix_connect_scene_on_exit,
    flipmatrix_how_to_connect_scene_on_exit,
    flipmatrix_about_scene_on_exit,
};

static const SceneManagerHandlers flipmatrix_scene_manager_handlers = {
    .on_enter_handlers = flipmatrix_scene_on_enter_handlers,
    .on_event_handlers = flipmatrix_scene_on_event_handlers,
    .on_exit_handlers = flipmatrix_scene_on_exit_handlers,
    .scene_num = FlipMatrixSceneCount,
};

static bool flipmatrix_custom_callback(void* context, uint32_t custom_event) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

bool flipmatrix_back_event_callback(void* context) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

static App* app_alloc() {
    App* app = malloc(sizeof(App));

    app->scene_manager = scene_manager_alloc(&flipmatrix_scene_manager_handlers, app);
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, flipmatrix_custom_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, flipmatrix_back_event_callback);

    app->submenu = submenu_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, FlipMatrixSubmenuView, submenu_get_view(app->submenu));

    app->widget = widget_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, FlipMatrixWidgetView, widget_get_view(app->widget));

    app->text_box = text_box_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, FlipMatrixTextBoxView, text_box_get_view(app->text_box));

    app->text_box_store = furi_string_alloc();

    // Initialize MAX7219 structure
    app->max7219 = malloc(sizeof(MAX7219));
    memset(app->max7219, 0, sizeof(MAX7219));
    app->matrix_connected = false;

    return app;
}
static void app_free(App* app) {
    furi_assert(app);

    // Deinitialize MAX7219 if connected
    if(app->matrix_connected && app->max7219) {
        max7219_deinit(app->max7219);
    }
    if(app->max7219) {
        free(app->max7219);
    }

    view_dispatcher_remove_view(app->view_dispatcher, FlipMatrixSubmenuView);
    view_dispatcher_remove_view(app->view_dispatcher, FlipMatrixWidgetView);
    view_dispatcher_remove_view(app->view_dispatcher, FlipMatrixTextBoxView);
    scene_manager_free(app->scene_manager);
    view_dispatcher_free(app->view_dispatcher);
    submenu_free(app->submenu);
    widget_free(app->widget);
    text_box_free(app->text_box);
    furi_string_free(app->text_box_store);
    free(app);
}

int32_t flipmatrix_app(void* p) {
    UNUSED(p);
    App* app = app_alloc();

    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, FlipMatrixMainMenuScene);
    view_dispatcher_run(app->view_dispatcher);

    app_free(app);
    return 0;
}
